# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/UMIDIGI/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/UMIDIGI/

PRODUCT_COPY_FILES += \
    vendor/UMIDIGI/A5_Pro/proprietary/bin/netd:$(TARGET_COPY_OUT_SYSTEM)/bin/netd \
    vendor/UMIDIGI/A5_Pro/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/UMIDIGI/A5_Pro/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libsysenv_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsysenv_system.so \
    vendor/UMIDIGI/A5_Pro/proprietary/framework/mediatek-ims-extension-plugin.jar:system/framework/mediatek-ims-extension-plugin.jar \
    vendor/UMIDIGI/A5_Pro/proprietary/framework/mediatek-ims-legacy.jar:system/framework/mediatek-ims-legacy.jar \
    vendor/UMIDIGI/A5_Pro/proprietary/framework/mediatek-ims-wwop-common.jar:system/framework/mediatek-ims-wwop-common.jar \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtk_vt_service.so:system/lib/libmtk_vt_service.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtk_vt_wrapper.so:system/lib/libmtk_vt_wrapper.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtkaudio_utils.so:system/lib/libmtkaudio_utils.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtkavenhancements.so:system/lib/libmtkavenhancements.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtkperf_client.so:system/lib/libmtkperf_client.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtk_serialnum.so:system/lib64/libmtk_serialnum.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtk_vt_wrapper.so:system/lib64/libmtk_vt_wrapper.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtkaudio_utils.so:system/lib64/libmtkaudio_utils.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtkavenhancements.so:system/lib64/libmtkavenhancements.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtkperf_client.so:system/lib64/libmtkperf_client.so \
    vendor/UMIDIGI/A5_Pro/proprietary/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    	
PRODUCT_PACKAGES += \
	ImsService \
    CameraGo \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common
